import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Makkan-Real Estate",
    description: "Generated by create next app",
    icons: {
      icon: "favicon.ico",
    },
  };